### ISSUE TITLE
Type variables not used in GADT constructors

### ISSUE THREAD

**Issue by srid** [obsidiansystems/aeson-gadt-th#14]
When not _all_ type variables of a GADT are used as arguments in its constructors, aeson deriving fails. For example, the following works:

```haskell
data View' v vm em :: * -> * where
  View'_GetVertexProperties :: v -> vm -> View' v vm em vm
  View'_GetEdgeProperties :: v -> v -> em -> View' v vm em em
```

But not this (which is the realistic type; note the absence of vm/em arguments):

```haskell
data View' v vm em :: * -> * where
  View'_GetVertexProperties :: v -> View' v vm em vm
  View'_GetEdgeProperties :: v -> v -> View' v vm em em
```

Compiler will throw an error that looks like:

```
    • Could not deduce (FromJSON topvar1)
        arising from a use of ‘parseJSON’
      from the context: FromJSON topvar
        bound by the instance declaration
        at common/src/Common/Types.hs:140:1-22
      Possible fix:
        add (FromJSON topvar1) to the context of the instance declaration
    • In a stmt of a 'do' block: (x_a1Zsf) <- parseJSON _v'_a1Zsk
      In the expression:
        do (x_a1Zsf) <- parseJSON _v'_a1Zsk
           return (This (View'_GetVertexProperties x_a1Zsf))
      In a case alternative:
          "View'_GetVertexProperties"
            -> do (x_a1Zsf) <- parseJSON _v'_a1Zsk
                  return (This (View'_GetVertexProperties x_a1Zsf))
    |
140 | deriveJSONGADT ''View'
    | ^^^^^^^^^^^^^^^^^^^^^^
```

In order to hack around it I ended up adding an unused dummy constructor:

```haskell
data View' v vm em :: * -> * where
  View'_Unused :: v -> vm -> em -> View' v vm em ()
  View'_GetVertexProperties :: v -> View' v vm em vm
  View'_GetEdgeProperties :: v -> v -> View' v vm em em
```

**Comment by cgibbard** [comment]
This one is interesting, I think I may need to just make it annotate the type
of the result of the parse so it's not ambiguous that we want it to be the
same as in the instance head. (Though I'm not entirely clear on why that seems to be the case.) Also I should try to make it use the
variables that the user used in their data declaration to help the errors
be a bit better when things fall over.

**Comment by cgibbard** [comment]
The fixes I just made should fix this. Get in touch if there's still something not working for which you can write the instances by hand.
