### ISSUE TITLE
Build failures with GHC-8.2 and older

### ISSUE THREAD

**Issue by phadej** [obsidiansystems/aeson-gadt-th#18]
```
Configuring library for aeson-gadt-th-0.2.1.1..
Preprocessing library for aeson-gadt-th-0.2.1.1..
Building library for aeson-gadt-th-0.2.1.1..
[1 of 1] Compiling Data.Aeson.GADT.TH ( src/Data/Aeson/GADT/TH.hs, /tmp/matrix-worker/1565052630/dist-newstyle/build/x86_64-linux/ghc-8.2.2/aeson-gadt-th-0.2.1.1/build/Data/Aeson/GADT/TH.o )

src/Data/Aeson/GADT/TH.hs:215:90: error:
    • Variable not in scope: (<>) :: t6 -> String -> t7
    • Perhaps you meant one of these:
        ‘<$>’ (imported from Prelude), ‘*>’ (imported from Prelude),
        ‘<$’ (imported from Prelude)
    |
215 |     findVar v _ _ = error $ "substVarsWith: couldn't look up variable substitution for " <> show v
    |                                                                                          ^^
```

EDIT: I made revisions to current releases e.g. https://hackage.haskell.org/package/aeson-gadt-th-0.2.1.1/revisions/
- old state: https://matrix.hackage.haskell.org/#/package/aeson-gadt-th/0.2.1.1/ghc-7.10.3@1570560151
- new state: https://matrix.hackage.haskell.org/#/package/aeson-gadt-th/0.1.2.0/ghc-8.6.5@1570562675 (0.1.2.0 is unfixable, though it's fine with `cabal v2-build` if `markdown-unlit` somehow happens to be in `$PATH`).

**Comment by ali-abrar** [comment]
GHC 8.0.2 works again as of v.0.2.1.2. That's the oldest version in our `tested-with`.
