### ISSUE TITLE
Fix version bounds on dependent-sum

### ISSUE THREAD

**Issue by Lysxia** [obsidiansystems/aeson-gadt-th#26]
aeson-gadt-th 0.2.1.1 and older are incompatible with dependent-sum 0.6.2.2 and newer (because the `This` constructor was removed). This causes cabal to pick up invalid build plans.

Fix: add an upper bound `dependent-sum < 0.6.2.2` on all versions of `aeson-gadt-th` prior to 0.2.1.1 (included).

In the latest release `aeson-gadt-th 0.2.2`, the existing upper bound `dependent-sum < 0.7` can also be relaxed to `dependent-sum < 0.8`.

**Comment by Lysxia** [comment]
Ping @ali-abrar 

Is this package still maintained? Should I just get Hackage trustees involved for this kind of issue?

**Comment by ali-abrar** [comment]
I've revised the packages <= v0.2.1.1 on hackage. As for relaxing the version constraint on the latest version, a PR showing that it doesn't cause an issue would be appreciated.
