### ISSUE TITLE
Build error with nix on macos

### ISSUE THREAD

**Issue by tgass** [obsidiansystems/aeson-gadt-th#7]
I try to build a project using aeson-gadt-th with nix (and reflex-platform) on macos and get this error. I'm not sure that this is the right place to file the issue. Hopefully you can help. Thank you!

-- 
(...)
cabal: Encountered missing dependencies:
aeson-gadt-th -any

[nix-shell:~/Documents/myProject]$ cabal install --dependencies-only
clang-5.0: warning: argument unused during compilation: '-nopie' [-Wunused-command-line-argument]
Resolving dependencies...
Configuring aeson-gadt-th-0.1.2.1...
Building aeson-gadt-th-0.1.2.1...
Failed to install aeson-gadt-th-0.1.2.1
Build log ( /Users/tilmann/.cabal/logs/ghc-8.4.3/aeson-gadt-th-0.1.2.1-7pYTkAwAT8T7XAxzdKa3k0.log ):
cabal: Entering directory '/var/folders/8m/b09mcrs1275dvkqb2mck9jnr0000gn/T/cabal-tmp-50429/aeson-gadt-th-0.1.2.1'
Configuring aeson-gadt-th-0.1.2.1...
clang-5.0: warning: argument unused during compilation: '-nopie' [-Wunused-command-line-argument]
Preprocessing library for aeson-gadt-th-0.1.2.1..
Building library for aeson-gadt-th-0.1.2.1..
[1 of 1] Compiling Data.Aeson.GADT.TH ( src/Data/Aeson/GADT/TH.hs, dist/build/Data/Aeson/GADT/TH.o )
ignoring (possibly broken) abi-depends field for packages
Preprocessing executable 'readme' for aeson-gadt-th-0.1.2.1..
Building executable 'readme' for aeson-gadt-th-0.1.2.1..
[1 of 1] Compiling Main             ( README.lhs, dist/build/readme/readme-tmp/Main.o )
Linking dist/build/readme/readme ...
clang-5.0: warning: argument unused during compilation: '-nopie' [-Wunused-command-line-argument]
clang-5.0: warning: argument unused during compilation: '-nopie' [-Wunused-command-line-argument]
Undefined symbols for architecture x86_64:
  "_iconv", referenced from:
      _hs_iconv in libHSbase-4.11.1.0.a(iconv.o)
     (maybe you meant: _base_GHCziIOziEncodingziIconv_iconvEncoding16_closure, _base_GHCziIOziEncodingziIconv_iconvEncoding1_info , _base_GHCziIOziEncodingziIconv_iconvEncoding3_closure , _base_GHCziIOziEncodingziIconv_iconvEncoding4_closure , _base_GHCziIOziEncodingziIconv_iconvEncoding10_closure , _base_GHCziIOziEncodingziIconv_iconvEncoding4_info , _base_GHCziIOziEncodingziIconv_iconvEncoding10_info , _hs_iconv , _base_GHCziIOziEncodingziIconv_iconvEncoding6_closure , _base_GHCziIOziEncodingziIconv_iconvEncoding7_closure , _base_GHCziIOziEncodingziIconv_iconvEncoding5_closure , _base_GHCziIOziEncodingziIconv_iconvEncoding8_bytes , _base_GHCziIOziEncodingziIconv_iconvEncoding7_info , _hs_iconv_open , _base_GHCziIOziEncodingziIconv_iconvEncoding15_closure , _base_GHCziIOziEncodingziIconv_iconvEncoding11_info , _base_GHCziIOziEncodingziIconv_iconvEncoding15_info , _base_GHCziIOziEncodingziIconv_iconvEncoding14_info , _base_GHCziIOziEncodingziIconv_iconvEncoding9_closure , _base_GHCziIOziEncodingziIconv_iconvEncoding16_info , _base_GHCziIOziEncodingziIconv_iconvEncoding14_closure , _base_GHCziIOziEncodingziIconv_iconvEncoding17_bytes , _base_GHCziIOziEncodingziIconv_iconvEncoding1_closure , _hs_iconv_close , _base_GHCziIOziEncodingziIconv_iconvEncoding2_info , _base_GHCziIOziEncodingziIconv_iconvEncoding11_closure , _base_GHCziIOziEncodingziIconv_iconvEncoding2_closure , _base_GHCziIOziEncodingziIconv_iconvEncoding13_bytes , _base_GHCziIOziEncodingziIconv_iconvEncoding18_info , _base_GHCziIOziEncodingziIconv_iconvEncoding12_closure , _base_GHCziIOziEncodingziIconv_iconvEncoding_info , _base_GHCziIOziEncodingziIconv_iconvEncoding_closure , _base_GHCziIOziEncodingziIconv_iconvEncoding18_closure , _base_GHCziIOziEncodingziIconv_iconvEncoding6_info , _base_GHCziIOziEncodingziIconv_iconvEncoding12_info )
  "_iconv_open", referenced from:
      _hs_iconv_open in libHSbase-4.11.1.0.a(iconv.o)
     (maybe you meant: _hs_iconv_open)
  "_iconv_close", referenced from:
      _hs_iconv_close in libHSbase-4.11.1.0.a(iconv.o)
     (maybe you meant: _hs_iconv_close)
  "_locale_charset", referenced from:
      _localeEncoding in libHSbase-4.11.1.0.a(PrelIOUtils.o)
ld: symbol(s) not found for architecture x86_64
clang-5.0: error: linker command failed with exit code 1 (use -v to see invocation)
`cc' failed in phase `Linker'. (Exit code: 1)
cabal: Leaving directory '/var/folders/8m/b09mcrs1275dvkqb2mck9jnr0000gn/T/cabal-tmp-50429/aeson-gadt-th-0.1.2.1'
cabal: Error: some packages failed to install:
aeson-gadt-th-0.1.2.1-7pYTkAwAT8T7XAxzdKa3k0 failed during the building phase.
The exception was:
ExitFailure 1

**Comment by ali-abrar** [comment]
Looks like an issue building the readme, probably due to the preprocessor we're using. It should be buildable on macOS but perhaps for now it's best to mark it buildable only on Linux. Are you able to build the library?

**Comment by ali-abrar** [comment]
What version of reflex-platform are you using? On a Mac, I was able to build this against the current tip of `develop` of reflex-platform. I used `reflex-platform/scripts/work-on ghc` and ran a cabal build from within the nix shell. The readme and the library built successfully.

**Comment by tgass** [comment]
Thank you for responding so quickly! That's really helpful! I guess then I haven't setup reflex-platform correctly. If you have a minute, just out of curiosity, does this work for you? I get this error, (also using latest develop branch). And I'll file with reflex-platform. Thanks!

MacBook-Pro-2:ipanema tilmann$ ./reflex-platform/scripts/work-on ghc aeson-gadt-th --show-trace


If you have any trouble with this script, please submit an issue at https://github.com/reflex-frp/reflex-platform/issues
error: while evaluating 'workOn' at /Users/tilmann/Documents/leksah/ipanema/reflex-platform/default.nix:673:29, called from (string):1:84:
while evaluating 'overrideCabal' at /Users/tilmann/Documents/leksah/ipanema/reflex-platform/default.nix:173:26, called from /Users/tilmann/Documents/leksah/ipanema/reflex-platform/default.nix:673:39:
while evaluating the attribute 'ghc.aeson-gadt-th' at /Users/tilmann/Documents/leksah/ipanema/reflex-platform/default.nix:472:10:
attribute 'aeson-gadt-th' missing, at (string):1:105

**Comment by ali-abrar** [comment]
@tgass Replace `aeson-gadt-th` in your command with `./aeson-gadt-th`

https://github.com/reflex-frp/reflex-platform/blob/develop/scripts/work-on#L9

**Comment by ali-abrar** [comment]
Feel free to reopen if this doesn't work. Thanks
